### ISSUE TITLE
Heroku App Checklist

### ISSUE THREAD

**Issue by xiaoyunyang** [xiaoyunyang/looseleaf-node#1]
- [X] Create User Account via Facebook
- [X] Create User Account via Github
- [X] Create User Account via Email and Local Strategy
- [ ] Enable csrf for the form used to submit user email and password
- [ ] List all users from GuestApp and UserApp
- [X] Server sends GuestApp if not logged in, and sends UserApp if logged in.
- [ ] Complete HowItWorks page. Serve content for the page from a markdown file.
- [ ] List some dummy data for the projects, which is hosted from JSON files stored on server
- [ ] Use settings page to see and modify user information
- [ ] Use settings page to delete user information
