### ISSUE TITLE
User settings Update Bugs

### ISSUE THREAD

**Issue by xiaoyunyang** [xiaoyunyang/looseleaf-node#8]
# Bug
- [x] Update redux store after user info changes (See TODO in [this file](https://github.com/xiaoyunyang/looseleaf-node/blob/master/client/src/shared/User/screens/Settings/Main.js)). Current behavior is after successfully updating user info in the database via the user settings page, when we navigate back to user profile page using the SPA, outdated info is still shown.
- [x] If user successfully changes username, have server redirect to the updated url with the new username. This would inevitably cause a page refresh.

# TODO
- [x] When user wants to change username, have the server check if the desired username is already taken. There's opportunity to have some code reuse with the local registration handler.
- [x] When user wants to change email, have the server check if the new email is not already taken.
- [ ] When user makes any request to the server to change User data, make sure this user is actually logged in.
- [x] If user successfully updates username, have the server redirect back to the settings page with the new username (different URL)

**Comment by xiaoyunyang** [comment]
- a02fc70 - Revised create username logic for local signup.
- 31c8bd7 - Revise new username creation logic for github and facebook signup
- 87e165a - Revised username creation and updating logic to account for existing username.
- 8fce134 - Revised  email updating logic to account for existing emails.
